services:

  mysql:
    image: mysql:8.0
    container_name: medilabo-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: medilabo_patient

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:8.0
    container_name: medilabo-mongo

    ports:
      - "27018:27017"

    volumes:
      - mongo-data:/data/db

  patient-service:
    build:
      context: ./patient-service

    container_name: medilabo-patient-service

    environment:
      DB_URL: jdbc:mysql://mysql:3306/medilabo_patient?serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "8081:8081"

    depends_on:
      mysql:
        condition: service_healthy

  notes-service:
    build:
      context: ./notes-service

    container_name: medilabo-notes-service

    environment:
      MONGO_URI: mongodb://mongo:27017/medilabo_notes

    ports:
      - "8083:8083"

    depends_on:
      - mongo

  risk-service:
    build:
      context: ./risk-service

    container_name: medilabo-risk-service

    environment:
      PATIENT_SERVICE_URL: http://patient-service:8081
      NOTE_SERVICE_URL: http://notes-service:8083

    ports:
      - "8084:8084"

    depends_on:
      - patient-service
      - notes-service

volumes:
  mysql-data:
  mongo-data: