spring.application.name=gateway-service

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=patient-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${PATIENT_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/patients/**

spring.cloud.gateway.server.webmvc.routes[1].id=notes-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${NOTES_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/notes/**

spring.cloud.gateway.server.webmvc.routes[2].id=risk-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${RISK_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/risk/**

jwt.secret=${JWT_SECRET}